'use strict';

const { webFrame, ipcRenderer } = require('electron');

// Neutralize beforeunload returnValues in the capture phase so playback does not
// trap navigations or window closure.
try {
  window.addEventListener(
    'beforeunload',
    (event) => {
      delete event.returnValue;
    },
    { capture: true },
  );
} catch {}

/**
 * The User-Agent *header* is rewritten in the main process, but
 * `navigator.userAgentData` is generated by Chromium itself and still lists an
 * "Electron" brand. Keep the JS-visible identity in step with the headers —
 * a contradiction between the two is exactly what Google's "this browser may not
 * be secure" check looks for.
 *
 * Preload runs in an isolated world, so patching from here would not be visible
 * to the page. `webFrame.executeJavaScript` evaluates in the page's main world,
 * and preload runs before any page script, so the patch lands first.
 */

function argValue(name) {
  return process.argv.find((arg) => arg.startsWith(`${name}=`))?.slice(name.length + 1);
}

const profileId = argValue('--ua-profile') ?? 'chrome';

/*
 * The Electron identity used on Google's sign-in pages is applied to the request
 * headers only — `navigator.userAgent` reports the browsing (Chrome) UA on every
 * page, because switching it per navigation breaks redirects. So the JS-visible
 * brands are patched everywhere too: whatever the wire says, what the page can
 * read about itself stays self-consistent.
 */
/** Diagnostics only: stops probe windows from raising a Windows Hello prompt. */
const disableWebAuthn = process.argv.includes('--disable-webauthn');

const BRANDS = {
  chrome: (major) => [
    { brand: 'Chromium', version: major },
    { brand: 'Google Chrome', version: major },
    { brand: 'Not_A Brand', version: '99' },
  ],
  edge: (major) => [
    { brand: 'Chromium', version: major },
    { brand: 'Microsoft Edge', version: major },
    { brand: 'Not_A Brand', version: '99' },
  ],
  firefox: () => null, // Firefox exposes no userAgentData at all
  electron: undefined, // leave Chromium's own value in place
};

function userAgentDataPatch(brands) {
  if (brands === undefined) return '';

  if (brands === null) {
    // Remove the property entirely, the way a non-Chromium browser looks.
    return `(() => {
      try { delete Navigator.prototype.userAgentData; } catch {}
      Object.defineProperty(navigator, 'userAgentData', {
        configurable: true, enumerable: false, get: () => undefined,
      });
    })();`;
  }

  return `(() => {
    const source = navigator.userAgentData;
    if (!source) return;
    const brands = Object.freeze(${JSON.stringify(brands)}.map((b) => Object.freeze({ ...b })));
    const patched = {
      brands,
      mobile: source.mobile,
      platform: source.platform,
      toJSON: () => ({ brands, mobile: source.mobile, platform: source.platform }),
      getHighEntropyValues: async (hints) => {
        const values = await source.getHighEntropyValues(hints);
        values.brands = brands;
        if ('fullVersionList' in values) {
          values.fullVersionList = brands.map((b) => ({ brand: b.brand, version: b.version + '.0.0.0' }));
        }
        if ('uaFullVersion' in values) values.uaFullVersion = brands[0].version + '.0.0.0';
        return values;
      },
    };
    Object.defineProperty(navigator, 'userAgentData', {
      configurable: true, enumerable: true, get: () => patched,
    });
  })();`;
}

/**
 * Diagnostics: report when a passkey ceremony starts and how it ends. Reported
 * through `console.error` on purpose — the main process already records console
 * output, so this needs no IPC bridge out of the page's main world.
 *
 * Off by default: wrapping `navigator.credentials` changes an object the page
 * can inspect, and the sign-in page is exactly where that is unwise.
 */
const webAuthnTrace = `(() => {
  if (!navigator.credentials) return;
  const wrap = (name) => {
    const original = navigator.credentials[name];
    if (typeof original !== 'function') return;
    navigator.credentials[name] = function (...args) {
      const started = Date.now();
      const options = args[0] && args[0].publicKey;
      console.error('[ytd-webauthn] ' + name + ' called', JSON.stringify({
        mediation: args[0] && args[0].mediation,
        rpId: options && options.rpId,
        userVerification: options && options.userVerification,
        allowCredentials: options && options.allowCredentials ? options.allowCredentials.length : undefined,
        timeout: options && options.timeout,
      }));
      return original.apply(this, args).then(
        (result) => {
          console.error('[ytd-webauthn] ' + name + ' resolved in ' + (Date.now() - started) + 'ms', !!result);
          return result;
        },
        (error) => {
          console.error('[ytd-webauthn] ' + name + ' rejected in ' + (Date.now() - started) + 'ms: ' + error.name + ' ' + error.message);
          throw error;
        },
      );
    };
  };
  wrap('get');
  wrap('create');
})();`;

const webAuthnStub = `(() => {
  if (!navigator.credentials) return;
  const refuse = () => Promise.reject(new DOMException('disabled for diagnostics', 'NotAllowedError'));
  navigator.credentials.get = refuse;
  navigator.credentials.create = refuse;
})();`;

const traceWebAuthn = process.argv.includes('--trace-webauthn');

const major = (/Chrome\/(\d+)/.exec(navigator.userAgent) ?? [, '0'])[1];
const patch = [
  userAgentDataPatch(BRANDS[profileId]?.(major)),
  disableWebAuthn ? webAuthnStub : '',
  traceWebAuthn && !disableWebAuthn ? webAuthnTrace : '',
]
  .filter(Boolean)
  .join('\n');

if (patch) {
  webFrame.executeJavaScript(patch).catch(() => {
    /* a page that refuses the patch still works; the UA header is the main signal */
  });
}

// ------------------------------------------------------------ user input ---

/**
 * Only real input counts. A page can call
 * `dispatchEvent(new MouseEvent('mousedown', { button: 2 }))` and forge an entire
 * gesture — and since this preload is injected into every frame, an ad iframe
 * could do it too. `isTrusted` is false for anything script-generated.
 */
const isRealInput = (event) => event.isTrusted === true;

// ------------------------------------------------------- video rotation ---

/**
 * `R` turns the video a quarter turn. Phone footage uploaded sideways is the
 * reason this exists.
 *
 * The transform is applied to the `<video>` element only, so the player controls
 * and the rest of the page stay upright.
 *
 * The geometry lives in the main process (`rotation.js`) and is fetched over
 * IPC. A sandboxed preload **cannot `require` application files** — only
 * `electron` and a handful of built-ins — and attempting it throws, taking every
 * listener registered further down this file with it. Duplicating the maths here
 * would work but would then drift away from the tested copy.
 */
let rotationAngle = 0;
/** @type {HTMLVideoElement | null} */
let rotatedVideo = null;

function findVideo() {
  return (
    document.querySelector('video.html5-main-video') ??
    document.querySelector('#movie_player video') ??
    document.querySelector('video')
  );
}

/**
 * Layout sizes, never `getBoundingClientRect()`.
 *
 * A bounding rect reflects the transform that is already applied, so measuring
 * an element that is currently rotated returns the rotated, scaled box. Feeding
 * that back in — which happens on every resize while rotated — compounds the
 * scaling until the video shrinks away. `offsetWidth` and `clientWidth` are
 * layout values and ignore transforms.
 */
function measure(video) {
  const player = video.closest('#movie_player') ?? video.parentElement ?? video;
  return {
    box: { width: video.offsetWidth, height: video.offsetHeight },
    container: { width: player.clientWidth, height: player.clientHeight },
  };
}

/**
 * Applied as a stylesheet rule rather than an inline style. YouTube rewrites the
 * video element's `style` attribute as the player resizes, and swaps the element
 * itself out on navigation — either would drop an inline transform, while a rule
 * keeps applying.
 */
/** @type {ResizeObserver | null} */
let playerObserver = null;

/**
 * Recompute when the player itself changes size.
 *
 * Going fullscreen fires `fullscreenchange` before the player has been laid out
 * at its new size, so recomputing on that event alone reads stale dimensions and
 * the video ends up scaled for the old box. Watching the element covers
 * fullscreen, theatre mode and window resizes alike, and always after the fact.
 *
 * A transform does not affect layout, so applying one cannot retrigger this.
 */
function observePlayer(video) {
  if (typeof ResizeObserver !== 'function') return;
  const player = video.closest('#movie_player') ?? video.parentElement;
  if (!player) return;

  playerObserver?.disconnect();
  playerObserver = new ResizeObserver(() => {
    if (rotationAngle) applyRotation(false);
  });
  playerObserver.observe(player);
}

function rotationStyleElement() {
  let style = document.getElementById('ytd-rotation-style');
  if (!style) {
    style = document.createElement('style');
    style.id = 'ytd-rotation-style';
    (document.head ?? document.documentElement).appendChild(style);
  }
  return style;
}

/**
 * One rotation at a time.
 *
 * Each call is a round trip to the main process, and a resize can land in the
 * middle of a keypress. Overlapping calls read `rotationAngle` before the other
 * has written it back, so a quarter turn goes missing — registering the resize
 * observer alone was enough to lose one, because observing fires immediately.
 */
let rotationQueue = Promise.resolve();

function applyRotation(advance) {
  rotationQueue = rotationQueue.then(() => rotateNow(advance)).catch(() => {});
  return rotationQueue;
}

async function rotateNow(advance) {
  const video = findVideo();
  if (!video) return;

  if (video !== rotatedVideo) {
    // A new video means a fresh start; carrying a rotation into the next
    // autoplayed clip would be baffling.
    if (rotatedVideo) rotationAngle = 0;
    rotatedVideo = video;
    observePlayer(video);
  }

  const { box, container } = measure(video);
  const result = await ipcRenderer.invoke('ytd:rotate', {
    current: rotationAngle,
    advance: advance === true,
    box,
    container,
  });

  rotationAngle = result.angle;
  rotationStyleElement().textContent = result.transform
    ? `video.html5-main-video, #movie_player video { transform: ${result.transform}; transform-origin: center center; }`
    : '';
}

/** Typing in the search box must stay typing. */
function isTypingTarget(target) {
  if (!target || typeof target.tagName !== 'string') return false;
  if (target.isContentEditable) return true;
  return ['INPUT', 'TEXTAREA', 'SELECT'].includes(target.tagName);
}

addEventListener(
  'keydown',
  (event) => {
    if (!isRealInput(event) || event.key !== 'r' || isTypingTarget(event.target)) return;
    // Ctrl+R is reload, and Alt/Meta combinations belong to the OS or the page.
    if (event.ctrlKey || event.altKey || event.metaKey) return;
    if (!findVideo()) return; // nothing to rotate; leave the key to the page

    event.preventDefault();
    event.stopPropagation();
    applyRotation(true);
  },
  true,
);

// The player resizes on window changes, theatre mode and fullscreen; the scale
// has to be recomputed or the video stops fitting.
addEventListener('resize', () => rotationAngle && applyRotation(false));
addEventListener('fullscreenchange', () => rotationAngle && applyRotation(false));

// --------------------------------------------------------- mouse gestures ---

/**
 * Hold the right mouse button and drag: ← back, → forward, ↓ then → close.
 *
 * Listeners run in the capture phase so the gesture is measured even on pages
 * that swallow mouse events (the YouTube player does). Preload shares the DOM
 * with the page, so no main-world injection is needed here.
 *
 * Only the path is recorded; `gesture.js` decides what it means.
 */
const gestureThreshold = Number(argValue('--gesture-threshold') ?? 60);

/** Sampling distance for the path, and a cap so a long drag cannot grow forever. */
const PATH_SAMPLE_PX = 12;
const PATH_MAX_POINTS = 128;

/** @type {{ x: number, y: number } | null} */
let dragOrigin = null;
/** @type {{ x: number, y: number }[]} */
let dragPath = [];
/** Furthest the pointer has been from the origin, in any direction. */
let maxTravel = 0;
let swallowContextMenu = false;

/**
 * Viewport coordinates. `screenX`/`screenY` look tempting but are not always
 * populated — injected input reports them as 0 — and the page does not scroll
 * during a right-button drag, so there is nothing for viewport coords to lose.
 */
const originOf = (event) => ({ x: event.clientX, y: event.clientY });

addEventListener(
  'mousedown',
  (event) => {
    if (!isRealInput(event) || event.button !== 2) return;
    dragOrigin = originOf(event);
    dragPath = [dragOrigin];
    maxTravel = 0;
    swallowContextMenu = false;
  },
  true,
);

addEventListener(
  'mousemove',
  (event) => {
    if (!isRealInput(event) || !dragOrigin) return;
    const point = originOf(event);
    maxTravel = Math.max(maxTravel, Math.hypot(point.x - dragOrigin.x, point.y - dragOrigin.y));

    // Sample rather than record every pixel: enough shape to find the corner of
    // an L, without a thousand points to ship over IPC.
    const last = dragPath.at(-1);
    if (Math.hypot(point.x - last.x, point.y - last.y) < PATH_SAMPLE_PX) return;
    if (dragPath.length >= PATH_MAX_POINTS) dragPath.shift();
    dragPath.push(point);
  },
  true,
);

addEventListener(
  'mouseup',
  (event) => {
    if (!isRealInput(event) || event.button !== 2 || !dragOrigin) return;
    const end = originOf(event);
    const dx = end.x - dragOrigin.x;
    const dy = end.y - dragOrigin.y;
    const path = [...dragPath, end];
    const travelled = Math.max(maxTravel, Math.hypot(dx, dy));
    dragOrigin = null;
    dragPath = [];

    // Travel in any direction counts: an L-shape can end up near where it
    // started on one axis while still being a deliberate gesture.
    if (travelled < gestureThreshold) return;
    swallowContextMenu = true;
    ipcRenderer.send('ytd:gesture', { dx, dy, path });
  },
  true,
);

addEventListener(
  'contextmenu',
  (event) => {
    // Windows fires contextmenu after mouseup, but not every platform agrees, so
    // also check whether the drag currently in progress already qualifies.
    const draggedFar = dragOrigin !== null && maxTravel >= gestureThreshold;
    if (!swallowContextMenu && !draggedFar) return;

    swallowContextMenu = false;
    event.preventDefault();
    event.stopPropagation();
  },
  true,
);

// ---------------------------------------------------- mode switcher UI ---

/**
 * Modern floating glassmorphic mode switcher (YouTube ⟷ YouTube Music).
 * Injected exclusively into the top-level YouTube frame inside an isolated Shadow DOM.
 */
function setupModeSwitcher() {
  if (window.top !== window.self) return;
  // Popups opened by window.open / ctrl-click should not have the switcher
  if (window.opener) return;

  const hostname = location.hostname;
  // Never inject into Google sign-in or consent frames
  if (hostname === 'accounts.google.com' || hostname === 'consent.google.com') return;
  if (!hostname.includes('youtube.com') && !hostname.includes('youtu.be')) return;

  let currentMode = hostname.includes('music.youtube.com') ? 'music' : 'youtube';
  let isHidden = localStorage.getItem('ytd:switcher-hidden') === 'true';
  let isPinned = localStorage.getItem('ytd:switcher-pinned') === 'true';

  const host = document.createElement('div');
  host.id = 'ytd-mode-switcher-host';
  host.style.cssText = 'position:fixed;top:0;left:0;width:0;height:0;pointer-events:none;z-index:2147483647;';
  const shadow = host.attachShadow({ mode: 'open' });

  const style = document.createElement('style');
  style.textContent = `
    :host {
      all: initial;
      position: fixed;
      top: 0;
      left: 0;
      width: 100%;
      height: 0;
      overflow: visible;
      z-index: 2147483647;
      pointer-events: none;
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
      user-select: none;
      -webkit-user-select: none;
    }

    :host(.fullscreen) .ytd-pulldown-host {
      opacity: 0 !important;
      pointer-events: none !important;
      transform: translateY(-100%) !important;
    }

    /*
     * STATIONARY HITBOX HOST
     * Pinned at top: 0. Never translates down!
     * Covers from window ceiling down through the expanded switcher with generous padding.
     */
    .ytd-pulldown-host {
      position: fixed;
      top: 0;
      left: 72px;
      width: 220px;
      height: 20px; /* Idle hit zone covers ceiling and peek tab */
      z-index: 2147483647;
      pointer-events: auto;
      cursor: default;
      display: flex;
      justify-content: center;
      transition: height 0.18s ease;
    }

    .ytd-pulldown-host.hidden {
      display: none !important;
    }

    /* Expanded hit zone covers ceiling all the way past the buttons with safe margins */
    .ytd-pulldown-host.expanded,
    .ytd-pulldown-host.pinned {
      height: 66px;
    }

    .ytd-pulldown-host.idle:not(.expanded):not(.pinned) {
      opacity: 0.35;
    }

    /*
     * INNER ANIMATED BODY
     * Animates down with spring bounce while host stays firmly anchored at top: 0
     */
    .ytd-pulldown-body {
      position: absolute;
      top: 0;
      left: 50%;
      transform: translateX(-50%) translateY(calc(-100% + 10px));
      display: flex;
      flex-direction: column;
      align-items: center;
      transition: transform 0.32s cubic-bezier(0.25, 0.8, 0.25, 1);
      will-change: transform;
      pointer-events: auto;
    }

    /* Bouncy spring expansion ("통통" 탄성 모션) */
    .ytd-pulldown-host.expanded .ytd-pulldown-body,
    .ytd-pulldown-host.pinned .ytd-pulldown-body,
    .ytd-pulldown-host.bouncing .ytd-pulldown-body {
      transform: translateX(-50%) translateY(7px);
      transition: transform 0.44s cubic-bezier(0.34, 1.56, 0.64, 1);
    }

    /* Main Glassmorphic Pill Container */
    .ytd-pill-container {
      display: flex;
      align-items: center;
      position: relative;
      height: 34px;
      padding: 3px;
      box-sizing: border-box;
      background: rgba(18, 18, 18, 0.95);
      backdrop-filter: blur(24px) saturate(180%);
      -webkit-backdrop-filter: blur(24px) saturate(180%);
      border: 1px solid rgba(255, 255, 255, 0.18);
      border-radius: 9999px;
      box-shadow:
        0 14px 38px rgba(0, 0, 0, 0.8),
        0 3px 10px rgba(0, 0, 0, 0.5),
        inset 0 1px 0 rgba(255, 255, 255, 0.22);
      gap: 2px;
      transition: border-color 0.2s ease, box-shadow 0.2s ease;
    }

    .ytd-pulldown-host.expanded .ytd-pill-container,
    .ytd-pulldown-host.pinned .ytd-pill-container {
      border-color: rgba(255, 255, 255, 0.28);
      box-shadow:
        0 16px 44px rgba(0, 0, 0, 0.85),
        0 4px 14px rgba(0, 0, 0, 0.55),
        0 0 22px rgba(255, 0, 0, 0.25),
        inset 0 1px 0 rgba(255, 255, 255, 0.3);
    }

    .ytd-pill-indicator {
      position: absolute;
      top: 3px;
      bottom: 3px;
      border-radius: 9999px;
      background: rgba(255, 255, 255, 0.14);
      border: 1px solid rgba(255, 255, 255, 0.18);
      pointer-events: none;
      transition: transform 0.26s cubic-bezier(0.2, 0.8, 0.2, 1), width 0.26s cubic-bezier(0.2, 0.8, 0.2, 1), box-shadow 0.26s ease;
    }

    .ytd-pill-container[data-active="youtube"] .ytd-pill-indicator {
      box-shadow: 0 0 14px rgba(255, 0, 0, 0.45);
    }

    .ytd-pill-container[data-active="music"] .ytd-pill-indicator {
      box-shadow: 0 0 14px rgba(255, 45, 65, 0.5);
    }

    .ytd-mode-btn {
      display: flex;
      align-items: center;
      gap: 6px;
      height: 28px;
      padding: 0 11px 0 9px;
      border: none;
      background: transparent;
      color: rgba(255, 255, 255, 0.65);
      font-size: 12.5px;
      font-weight: 600;
      letter-spacing: 0.15px;
      border-radius: 9999px;
      cursor: pointer;
      position: relative;
      z-index: 2;
      transition: color 0.18s ease, transform 0.12s ease;
      outline: none;
      white-space: nowrap;
    }

    .ytd-mode-btn:hover { color: #ffffff; }
    .ytd-mode-btn:active { transform: scale(0.96); }
    .ytd-mode-btn.active { color: #ffffff; }

    .ytd-icon {
      display: flex;
      align-items: center;
      justify-content: center;
      flex-shrink: 0;
    }

    .ytd-kbd {
      font-size: 10px;
      opacity: 0.55;
      margin-left: 2px;
      font-weight: 500;
    }

    .ytd-divider {
      width: 1px;
      height: 15px;
      background: rgba(255, 255, 255, 0.16);
      margin: 0 2px;
    }

    .ytd-pin-btn {
      display: flex;
      align-items: center;
      justify-content: center;
      width: 24px;
      height: 24px;
      border-radius: 50%;
      border: none;
      background: transparent;
      color: rgba(255, 255, 255, 0.4);
      cursor: pointer;
      transition: all 0.18s ease;
      outline: none;
      margin-right: 2px;
    }

    .ytd-pin-btn:hover {
      color: #ffffff;
      background: rgba(255, 255, 255, 0.12);
    }

    .ytd-pin-btn.active {
      color: #ff334b;
      background: rgba(255, 45, 65, 0.18);
    }

    /* Peek pull tab hanging down from ceiling */
    .ytd-peek-tab {
      width: 82px;
      height: 10px;
      background: rgba(18, 18, 18, 0.95);
      backdrop-filter: blur(20px) saturate(180%);
      -webkit-backdrop-filter: blur(20px) saturate(180%);
      border: 1px solid rgba(255, 255, 255, 0.22);
      border-top: none;
      border-radius: 0 0 11px 11px;
      display: flex;
      align-items: center;
      justify-content: center;
      cursor: pointer;
      box-shadow: 0 4px 14px rgba(0, 0, 0, 0.6);
      transition: width 0.24s ease, height 0.24s ease, border-color 0.2s ease, background 0.2s ease;
      margin-top: -1px;
    }

    .ytd-pulldown-host.expanded .ytd-peek-tab,
    .ytd-pulldown-host.pinned .ytd-peek-tab {
      width: 48px;
      height: 6px;
      border-radius: 0 0 8px 8px;
      background: rgba(28, 28, 28, 0.85);
      border-color: rgba(255, 255, 255, 0.14);
    }

    .ytd-peek-handle {
      display: flex;
      align-items: center;
      justify-content: center;
      gap: 4px;
      pointer-events: none;
    }

    .ytd-peek-dot {
      width: 4px;
      height: 4px;
      border-radius: 50%;
      background: #ff0000;
      box-shadow: 0 0 6px #ff0000;
      transition: opacity 0.2s ease;
    }

    .ytd-pulldown-host.expanded .ytd-peek-dot,
    .ytd-pulldown-host.pinned .ytd-peek-dot {
      display: none;
    }

    .ytd-peek-bar {
      width: 24px;
      height: 3px;
      border-radius: 9999px;
      background: rgba(255, 255, 255, 0.5);
      transition: width 0.2s ease, opacity 0.2s ease;
    }

    .ytd-pulldown-host.expanded .ytd-peek-bar,
    .ytd-pulldown-host.pinned .ytd-peek-bar {
      width: 16px;
      opacity: 0.35;
    }

    /* HUD Toast Notification */
    .ytd-hud-toast {
      position: fixed;
      top: 24px;
      left: 50%;
      transform: translateX(-50%) translateY(-60px);
      display: flex;
      align-items: center;
      gap: 10px;
      padding: 8px 20px;
      border-radius: 9999px;
      background: rgba(15, 15, 15, 0.94);
      backdrop-filter: blur(24px) saturate(180%);
      -webkit-backdrop-filter: blur(24px) saturate(180%);
      border: 1px solid rgba(255, 255, 255, 0.2);
      box-shadow: 0 14px 40px rgba(0, 0, 0, 0.65), inset 0 1px 0 rgba(255, 255, 255, 0.22);
      color: #ffffff;
      font-size: 13.5px;
      font-weight: 600;
      letter-spacing: 0.15px;
      opacity: 0;
      transition: transform 0.35s cubic-bezier(0.175, 0.885, 0.32, 1.25), opacity 0.28s ease;
      pointer-events: none;
      z-index: 2147483647;
    }

    .ytd-hud-toast.show {
      transform: translateX(-50%) translateY(0);
      opacity: 1;
    }
  `;

  shadow.appendChild(style);

  // Stationary Hitbox Host
  const hostEl = document.createElement('div');
  hostEl.className = 'ytd-pulldown-host' + (isPinned ? ' pinned' : '') + (isHidden ? ' hidden' : '');

  // Animated Body
  const bodyEl = document.createElement('div');
  bodyEl.className = 'ytd-pulldown-body';

  const container = document.createElement('div');
  container.className = 'ytd-pill-container';
  container.setAttribute('data-active', currentMode);

  const indicator = document.createElement('div');
  indicator.className = 'ytd-pill-indicator';

  const SVG_NS = 'http://www.w3.org/2000/svg';

  function createSvg(width, height, viewBox) {
    const svg = document.createElementNS(SVG_NS, 'svg');
    svg.setAttribute('width', String(width));
    svg.setAttribute('height', String(height));
    svg.setAttribute('viewBox', viewBox);
    return svg;
  }

  function createPath(d, fill, stroke) {
    const path = document.createElementNS(SVG_NS, 'path');
    path.setAttribute('d', d);
    if (fill) path.setAttribute('fill', fill);
    if (stroke) path.setAttribute('stroke', stroke);
    return path;
  }

  function createPolygon(points, fill) {
    const polygon = document.createElementNS(SVG_NS, 'polygon');
    polygon.setAttribute('points', points);
    if (fill) polygon.setAttribute('fill', fill);
    return polygon;
  }

  function createCircle(cx, cy, r, fill) {
    const circle = document.createElementNS(SVG_NS, 'circle');
    circle.setAttribute('cx', String(cx));
    circle.setAttribute('cy', String(cy));
    circle.setAttribute('r', String(r));
    if (fill) circle.setAttribute('fill', fill);
    return circle;
  }

  function createYouTubeIcon(width = 18, height = 14) {
    const svg = createSvg(width, height, '0 0 24 24');
    svg.classList.add('ytd-icon');
    svg.appendChild(
      createPath(
        'M23.5 6.2a3 3 0 0 0-2.1-2.1C19.5 3.5 12 3.5 12 3.5s-7.5 0-9.4.6A3 3 0 0 0 .5 6.2 31.6 31.6 0 0 0 0 12c0 2 .2 3.9.5 5.8a3 3 0 0 0 2.1 2.1c1.9.6 9.4.6 9.4.6s7.5 0 9.4-.6a3 3 0 0 0 2.1-2.1c.3-1.9.5-3.8.5-5.8 0-2-.2-3.9-.5-5.8z',
        '#FF0000',
      ),
    );
    svg.appendChild(createPolygon('9.6,15.6 15.9,12 9.6,8.4', '#FFFFFF'));
    return svg;
  }

  function createMusicIcon(size = 16) {
    const svg = createSvg(size, size, '0 0 24 24');
    svg.classList.add('ytd-icon');
    svg.appendChild(createCircle(12, 12, 11, '#FF0000'));
    svg.appendChild(createCircle(12, 12, 6.2, '#141414'));
    svg.appendChild(createPolygon('10.2,8.8 15.2,12 10.2,15.2', '#FFFFFF'));
    return svg;
  }

  function createPinIcon(size = 12) {
    const svg = createSvg(size, size, '0 0 24 24');
    svg.setAttribute('fill', 'none');
    svg.setAttribute('stroke', 'currentColor');
    svg.setAttribute('stroke-width', '2');
    svg.setAttribute('stroke-linecap', 'round');
    svg.setAttribute('stroke-linejoin', 'round');
    const path = createPath('M12 17v5M5 7l7-4 7 4-2 7H7L5 7z', 'none', 'currentColor');
    svg.appendChild(path);
    return svg;
  }

  // YouTube Button
  const ytBtn = document.createElement('button');
  ytBtn.className = 'ytd-mode-btn' + (currentMode === 'youtube' ? ' active' : '');
  ytBtn.title = 'YouTube (Ctrl+1)';
  const ytIconSpan = document.createElement('span');
  ytIconSpan.className = 'ytd-icon';
  ytIconSpan.appendChild(createYouTubeIcon());
  const ytLabel = document.createElement('span');
  ytLabel.textContent = 'YouTube';
  const ytKbd = document.createElement('span');
  ytKbd.className = 'ytd-kbd';
  ytKbd.textContent = '^1';
  ytBtn.appendChild(ytIconSpan);
  ytBtn.appendChild(ytLabel);
  ytBtn.appendChild(ytKbd);

  // Music Button
  const musicBtn = document.createElement('button');
  musicBtn.className = 'ytd-mode-btn' + (currentMode === 'music' ? ' active' : '');
  musicBtn.title = 'YouTube Music (Ctrl+2)';
  const musicIconSpan = document.createElement('span');
  musicIconSpan.className = 'ytd-icon';
  musicIconSpan.appendChild(createMusicIcon());
  const musicLabel = document.createElement('span');
  musicLabel.textContent = 'Music';
  const musicKbd = document.createElement('span');
  musicKbd.className = 'ytd-kbd';
  musicKbd.textContent = '^2';
  musicBtn.appendChild(musicIconSpan);
  musicBtn.appendChild(musicLabel);
  musicBtn.appendChild(musicKbd);

  const divider = document.createElement('div');
  divider.className = 'ytd-divider';

  // Pin button (keep open)
  const pinBtn = document.createElement('button');
  pinBtn.className = 'ytd-pin-btn' + (isPinned ? ' active' : '');
  pinBtn.title = isPinned ? '고정 해제 (호버 시에만 펼치기)' : '고정 (항상 펼침 유지)';
  pinBtn.appendChild(createPinIcon());

  container.appendChild(indicator);
  container.appendChild(ytBtn);
  container.appendChild(musicBtn);
  container.appendChild(divider);
  container.appendChild(pinBtn);

  // Peek Pull Tab at bottom of body
  const peekTab = document.createElement('div');
  peekTab.className = 'ytd-peek-tab';
  peekTab.title = '마우스를 올리거나 클릭하면 모드 전환 스위치가 펼쳐집니다';

  const peekHandle = document.createElement('div');
  peekHandle.className = 'ytd-peek-handle';
  const peekDot = document.createElement('span');
  peekDot.className = 'ytd-peek-dot';
  const peekBar = document.createElement('span');
  peekBar.className = 'ytd-peek-bar';
  peekHandle.appendChild(peekDot);
  peekHandle.appendChild(peekBar);
  peekTab.appendChild(peekHandle);

  bodyEl.appendChild(container);
  bodyEl.appendChild(peekTab);
  hostEl.appendChild(bodyEl);
  shadow.appendChild(hostEl);

  // HUD Toast
  const hudToast = document.createElement('div');
  hudToast.className = 'ytd-hud-toast';
  shadow.appendChild(hudToast);

  let toastTimer = null;
  function showToast(mode) {
    clearTimeout(toastTimer);
    const isMusic = mode === 'music';
    hudToast.replaceChildren();
    const iconSpan = document.createElement('span');
    iconSpan.className = 'ytd-icon';
    iconSpan.appendChild(isMusic ? createMusicIcon(18) : createYouTubeIcon(20, 15));
    const label = document.createElement('span');
    label.textContent = isMusic ? 'YouTube Music 모드로 전환' : 'YouTube 모드로 전환';
    hudToast.appendChild(iconSpan);
    hudToast.appendChild(label);
    hudToast.classList.add('show');
    toastTimer = setTimeout(() => {
      hudToast.classList.remove('show');
    }, 1800);
  }

  function updateIndicator(mode = currentMode) {
    currentMode = mode;
    container.setAttribute('data-active', mode);
    ytBtn.classList.toggle('active', mode === 'youtube');
    musicBtn.classList.toggle('active', mode === 'music');

    const activeBtn = mode === 'music' ? musicBtn : ytBtn;
    if (activeBtn && activeBtn.offsetWidth > 0) {
      indicator.style.transform = `translateX(${activeBtn.offsetLeft}px)`;
      indicator.style.width = `${activeBtn.offsetWidth}px`;
    }
  }

  function pauseAllMedia() {
    try {
      const mediaList = document.querySelectorAll('video, audio');
      mediaList.forEach((media) => {
        try {
          media.pause();
        } catch {}
      });
    } catch {}
  }

  function triggerBouncySwitch(targetMode) {
    pauseAllMedia();
    updateIndicator(targetMode);
    showToast(targetMode);

    clearTimeout(retractTimer);
    hostEl.classList.add('bouncing');
    hostEl.classList.add('expanded');

    // Keep open for 1.8 seconds on shortcut trigger, then calmly retract if not pinned
    retractTimer = setTimeout(() => {
      hostEl.classList.remove('bouncing');
      if (!isPinned) hostEl.classList.remove('expanded');
    }, 1800);

    ipcRenderer.invoke('ytd:switch-mode', { target: targetMode });
  }

  // Hover & Retract logic with 750ms hysteresis delay (deliberately sluggish and rock-solid)
  let retractTimer = null;
  hostEl.addEventListener('mouseenter', () => {
    clearTimeout(retractTimer);
    hostEl.classList.add('expanded');
    requestAnimationFrame(() => updateIndicator(currentMode));
  });

  hostEl.addEventListener('mouseleave', () => {
    if (isPinned) return;
    clearTimeout(retractTimer);
    // 750ms grace delay: eliminates any flickering/bobbing when hovering around buttons
    retractTimer = setTimeout(() => {
      hostEl.classList.remove('expanded');
    }, 750);
  });

  // Pin toggle
  const togglePin = (e) => {
    e?.stopPropagation();
    isPinned = !isPinned;
    hostEl.classList.toggle('pinned', isPinned);
    pinBtn.classList.toggle('active', isPinned);
    pinBtn.title = isPinned ? '고정 해제 (호버 시에만 펼치기)' : '고정 (항상 펼침 유지)';
    localStorage.setItem('ytd:switcher-pinned', String(isPinned));
    if (isPinned) {
      clearTimeout(retractTimer);
      hostEl.classList.add('expanded');
    }
  };
  pinBtn.addEventListener('click', togglePin);
  peekTab.addEventListener('click', togglePin);

  // Interaction handlers
  ytBtn.addEventListener('click', (e) => {
    e.stopPropagation();
    if (currentMode !== 'youtube') {
      triggerBouncySwitch('youtube');
    }
  });

  musicBtn.addEventListener('click', (e) => {
    e.stopPropagation();
    if (currentMode !== 'music') {
      triggerBouncySwitch('music');
    }
  });

  // Align above YouTube / YouTube Music logo
  function alignWithLogo() {
    const logo = document.querySelector('ytmusic-logo, ytd-topbar-logo-renderer#logo, a#logo, #logo');
    if (logo) {
      const rect = logo.getBoundingClientRect();
      if (rect.left > 10 && rect.left < 260) {
        const logoCenter = rect.left + rect.width / 2;
        const hostLeft = Math.max(16, Math.round(logoCenter - 110));
        hostEl.style.left = `${hostLeft}px`;
        return;
      }
    }
    hostEl.style.left = '72px';
  }

  // Fullscreen handling
  const checkFullscreen = () => {
    const isFullscreen = !!document.fullscreenElement;
    host.classList.toggle('fullscreen', isFullscreen);
  };
  document.addEventListener('fullscreenchange', checkFullscreen);
  checkFullscreen();

  // Idle dimming while watching
  let idleTimer = null;
  const resetIdle = () => {
    hostEl.classList.remove('idle');
    clearTimeout(idleTimer);
    if (location.pathname === '/watch') {
      idleTimer = setTimeout(() => {
        hostEl.classList.add('idle');
      }, 3500);
    }
  };
  window.addEventListener('mousemove', resetIdle, { passive: true });
  window.addEventListener('keydown', resetIdle, { passive: true });
  resetIdle();

  // IPC listeners
  ipcRenderer.on('ytd:mode-updated', (_event, data) => {
    if (data?.mode) {
      updateIndicator(data.mode);
      showToast(data.mode);
    }
  });

  const toggleVisibility = () => {
    isHidden = !isHidden;
    hostEl.classList.toggle('hidden', isHidden);
    localStorage.setItem('ytd:switcher-hidden', String(isHidden));
  };
  ipcRenderer.on('ytd:toggle-switcher', toggleVisibility);

  // Keyboard Shortcuts: Ctrl+1, Ctrl+2, Ctrl+M, Ctrl+Shift+M
  window.addEventListener(
    'keydown',
    (event) => {
      if (event.ctrlKey && !event.altKey && !event.metaKey) {
        if (!event.shiftKey && event.key === '1') {
          event.preventDefault();
          triggerBouncySwitch('youtube');
        } else if (!event.shiftKey && event.key === '2') {
          event.preventDefault();
          triggerBouncySwitch('music');
        } else if (!event.shiftKey && (event.key === 'm' || event.key === 'M')) {
          event.preventDefault();
          const next = currentMode === 'music' ? 'youtube' : 'music';
          triggerBouncySwitch(next);
        } else if (event.shiftKey && (event.key === 'M' || event.key === 'm')) {
          event.preventDefault();
          toggleVisibility();
        }
      }
    },
    true,
  );

  // Mount
  const mount = () => {
    if (!document.documentElement.contains(host)) {
      document.documentElement.appendChild(host);
      alignWithLogo();
      requestAnimationFrame(() => updateIndicator(currentMode));
    }
  };

  if (document.documentElement) mount();
  window.addEventListener('DOMContentLoaded', () => {
    mount();
    alignWithLogo();
  });
  window.addEventListener('resize', () => {
    alignWithLogo();
    requestAnimationFrame(() => updateIndicator(currentMode));
  });

  // Observe DOM for logo element appearance
  const observer = new MutationObserver(() => alignWithLogo());
  if (document.body) {
    observer.observe(document.body, { childList: true, subtree: false });
  }
}

setupModeSwitcher();

