'use strict';

const { webFrame, ipcRenderer } = require('electron');

/**
 * The User-Agent *header* is rewritten in the main process, but
 * `navigator.userAgentData` is generated by Chromium itself and still lists an
 * "Electron" brand. Keep the JS-visible identity in step with the headers —
 * a contradiction between the two is exactly what Google's "this browser may not
 * be secure" check looks for.
 *
 * Preload runs in an isolated world, so patching from here would not be visible
 * to the page. `webFrame.executeJavaScript` evaluates in the page's main world,
 * and preload runs before any page script, so the patch lands first.
 */

function argValue(name) {
  return process.argv.find((arg) => arg.startsWith(`${name}=`))?.slice(name.length + 1);
}

const profileId = argValue('--ua-profile') ?? 'chrome';

/*
 * The Electron identity used on Google's sign-in pages is applied to the request
 * headers only — `navigator.userAgent` reports the browsing (Chrome) UA on every
 * page, because switching it per navigation breaks redirects. So the JS-visible
 * brands are patched everywhere too: whatever the wire says, what the page can
 * read about itself stays self-consistent.
 */
/** Diagnostics only: stops probe windows from raising a Windows Hello prompt. */
const disableWebAuthn = process.argv.includes('--disable-webauthn');

const BRANDS = {
  chrome: (major) => [
    { brand: 'Chromium', version: major },
    { brand: 'Google Chrome', version: major },
    { brand: 'Not_A Brand', version: '99' },
  ],
  edge: (major) => [
    { brand: 'Chromium', version: major },
    { brand: 'Microsoft Edge', version: major },
    { brand: 'Not_A Brand', version: '99' },
  ],
  firefox: () => null, // Firefox exposes no userAgentData at all
  electron: undefined, // leave Chromium's own value in place
};

function userAgentDataPatch(brands) {
  if (brands === undefined) return '';

  if (brands === null) {
    // Remove the property entirely, the way a non-Chromium browser looks.
    return `(() => {
      try { delete Navigator.prototype.userAgentData; } catch {}
      Object.defineProperty(navigator, 'userAgentData', {
        configurable: true, enumerable: false, get: () => undefined,
      });
    })();`;
  }

  return `(() => {
    const source = navigator.userAgentData;
    if (!source) return;
    const brands = Object.freeze(${JSON.stringify(brands)}.map((b) => Object.freeze({ ...b })));
    const patched = {
      brands,
      mobile: source.mobile,
      platform: source.platform,
      toJSON: () => ({ brands, mobile: source.mobile, platform: source.platform }),
      getHighEntropyValues: async (hints) => {
        const values = await source.getHighEntropyValues(hints);
        values.brands = brands;
        if ('fullVersionList' in values) {
          values.fullVersionList = brands.map((b) => ({ brand: b.brand, version: b.version + '.0.0.0' }));
        }
        if ('uaFullVersion' in values) values.uaFullVersion = brands[0].version + '.0.0.0';
        return values;
      },
    };
    Object.defineProperty(navigator, 'userAgentData', {
      configurable: true, enumerable: true, get: () => patched,
    });
  })();`;
}

/**
 * Diagnostics: report when a passkey ceremony starts and how it ends. Reported
 * through `console.error` on purpose — the main process already records console
 * output, so this needs no IPC bridge out of the page's main world.
 *
 * Off by default: wrapping `navigator.credentials` changes an object the page
 * can inspect, and the sign-in page is exactly where that is unwise.
 */
const webAuthnTrace = `(() => {
  if (!navigator.credentials) return;
  const wrap = (name) => {
    const original = navigator.credentials[name];
    if (typeof original !== 'function') return;
    navigator.credentials[name] = function (...args) {
      const started = Date.now();
      const options = args[0] && args[0].publicKey;
      console.error('[ytd-webauthn] ' + name + ' called', JSON.stringify({
        mediation: args[0] && args[0].mediation,
        rpId: options && options.rpId,
        userVerification: options && options.userVerification,
        allowCredentials: options && options.allowCredentials ? options.allowCredentials.length : undefined,
        timeout: options && options.timeout,
      }));
      return original.apply(this, args).then(
        (result) => {
          console.error('[ytd-webauthn] ' + name + ' resolved in ' + (Date.now() - started) + 'ms', !!result);
          return result;
        },
        (error) => {
          console.error('[ytd-webauthn] ' + name + ' rejected in ' + (Date.now() - started) + 'ms: ' + error.name + ' ' + error.message);
          throw error;
        },
      );
    };
  };
  wrap('get');
  wrap('create');
})();`;

const webAuthnStub = `(() => {
  if (!navigator.credentials) return;
  const refuse = () => Promise.reject(new DOMException('disabled for diagnostics', 'NotAllowedError'));
  navigator.credentials.get = refuse;
  navigator.credentials.create = refuse;
})();`;

const traceWebAuthn = process.argv.includes('--trace-webauthn');

const major = (/Chrome\/(\d+)/.exec(navigator.userAgent) ?? [, '0'])[1];
const patch = [
  userAgentDataPatch(BRANDS[profileId]?.(major)),
  disableWebAuthn ? webAuthnStub : '',
  traceWebAuthn && !disableWebAuthn ? webAuthnTrace : '',
]
  .filter(Boolean)
  .join('\n');

if (patch) {
  webFrame.executeJavaScript(patch).catch(() => {
    /* a page that refuses the patch still works; the UA header is the main signal */
  });
}

// ------------------------------------------------------------ user input ---

/**
 * Only real input counts. A page can call
 * `dispatchEvent(new MouseEvent('mousedown', { button: 2 }))` and forge an entire
 * gesture — and since this preload is injected into every frame, an ad iframe
 * could do it too. `isTrusted` is false for anything script-generated.
 */
const isRealInput = (event) => event.isTrusted === true;

// ------------------------------------------------------- video rotation ---

/**
 * `R` turns the video a quarter turn. Phone footage uploaded sideways is the
 * reason this exists.
 *
 * The transform is applied to the `<video>` element only, so the player controls
 * and the rest of the page stay upright.
 *
 * The geometry lives in the main process (`rotation.js`) and is fetched over
 * IPC. A sandboxed preload **cannot `require` application files** — only
 * `electron` and a handful of built-ins — and attempting it throws, taking every
 * listener registered further down this file with it. Duplicating the maths here
 * would work but would then drift away from the tested copy.
 */
let rotationAngle = 0;
/** @type {HTMLVideoElement | null} */
let rotatedVideo = null;

function findVideo() {
  return (
    document.querySelector('video.html5-main-video') ??
    document.querySelector('#movie_player video') ??
    document.querySelector('video')
  );
}

/**
 * Layout sizes, never `getBoundingClientRect()`.
 *
 * A bounding rect reflects the transform that is already applied, so measuring
 * an element that is currently rotated returns the rotated, scaled box. Feeding
 * that back in — which happens on every resize while rotated — compounds the
 * scaling until the video shrinks away. `offsetWidth` and `clientWidth` are
 * layout values and ignore transforms.
 */
function measure(video) {
  const player = video.closest('#movie_player') ?? video.parentElement ?? video;
  return {
    box: { width: video.offsetWidth, height: video.offsetHeight },
    container: { width: player.clientWidth, height: player.clientHeight },
  };
}

/**
 * Applied as a stylesheet rule rather than an inline style. YouTube rewrites the
 * video element's `style` attribute as the player resizes, and swaps the element
 * itself out on navigation — either would drop an inline transform, while a rule
 * keeps applying.
 */
function rotationStyleElement() {
  let style = document.getElementById('ytd-rotation-style');
  if (!style) {
    style = document.createElement('style');
    style.id = 'ytd-rotation-style';
    (document.head ?? document.documentElement).appendChild(style);
  }
  return style;
}

async function applyRotation(advance) {
  const video = findVideo();
  if (!video) return;

  // A new video means a fresh start; carrying a rotation into the next
  // autoplayed clip would be baffling.
  if (rotatedVideo && video !== rotatedVideo) rotationAngle = 0;
  rotatedVideo = video;

  const { box, container } = measure(video);
  const result = await ipcRenderer.invoke('ytd:rotate', {
    current: rotationAngle,
    advance: advance === true,
    box,
    container,
  });

  rotationAngle = result.angle;
  rotationStyleElement().textContent = result.transform
    ? `video.html5-main-video, #movie_player video { transform: ${result.transform}; transform-origin: center center; }`
    : '';
}

/** Typing in the search box must stay typing. */
function isTypingTarget(target) {
  if (!target || typeof target.tagName !== 'string') return false;
  if (target.isContentEditable) return true;
  return ['INPUT', 'TEXTAREA', 'SELECT'].includes(target.tagName);
}

addEventListener(
  'keydown',
  (event) => {
    if (!isRealInput(event) || event.key !== 'r' || isTypingTarget(event.target)) return;
    // Ctrl+R is reload, and Alt/Meta combinations belong to the OS or the page.
    if (event.ctrlKey || event.altKey || event.metaKey) return;
    if (!findVideo()) return; // nothing to rotate; leave the key to the page

    event.preventDefault();
    event.stopPropagation();
    applyRotation(true);
  },
  true,
);

// The player resizes on window changes, theatre mode and fullscreen; the scale
// has to be recomputed or the video stops fitting.
addEventListener('resize', () => rotationAngle && applyRotation(false));
addEventListener('fullscreenchange', () => rotationAngle && applyRotation(false));

// --------------------------------------------------------- mouse gestures ---

/**
 * Hold the right mouse button and drag: ← back, → forward, ↓ then → close.
 *
 * Listeners run in the capture phase so the gesture is measured even on pages
 * that swallow mouse events (the YouTube player does). Preload shares the DOM
 * with the page, so no main-world injection is needed here.
 *
 * Only the path is recorded; `gesture.js` decides what it means.
 */
const gestureThreshold = Number(argValue('--gesture-threshold') ?? 60);

/** Sampling distance for the path, and a cap so a long drag cannot grow forever. */
const PATH_SAMPLE_PX = 12;
const PATH_MAX_POINTS = 128;

/** @type {{ x: number, y: number } | null} */
let dragOrigin = null;
/** @type {{ x: number, y: number }[]} */
let dragPath = [];
/** Furthest the pointer has been from the origin, in any direction. */
let maxTravel = 0;
let swallowContextMenu = false;

/**
 * Viewport coordinates. `screenX`/`screenY` look tempting but are not always
 * populated — injected input reports them as 0 — and the page does not scroll
 * during a right-button drag, so there is nothing for viewport coords to lose.
 */
const originOf = (event) => ({ x: event.clientX, y: event.clientY });

addEventListener(
  'mousedown',
  (event) => {
    if (!isRealInput(event) || event.button !== 2) return;
    dragOrigin = originOf(event);
    dragPath = [dragOrigin];
    maxTravel = 0;
    swallowContextMenu = false;
  },
  true,
);

addEventListener(
  'mousemove',
  (event) => {
    if (!isRealInput(event) || !dragOrigin) return;
    const point = originOf(event);
    maxTravel = Math.max(maxTravel, Math.hypot(point.x - dragOrigin.x, point.y - dragOrigin.y));

    // Sample rather than record every pixel: enough shape to find the corner of
    // an L, without a thousand points to ship over IPC.
    const last = dragPath.at(-1);
    if (Math.hypot(point.x - last.x, point.y - last.y) < PATH_SAMPLE_PX) return;
    if (dragPath.length >= PATH_MAX_POINTS) dragPath.shift();
    dragPath.push(point);
  },
  true,
);

addEventListener(
  'mouseup',
  (event) => {
    if (!isRealInput(event) || event.button !== 2 || !dragOrigin) return;
    const end = originOf(event);
    const dx = end.x - dragOrigin.x;
    const dy = end.y - dragOrigin.y;
    const path = [...dragPath, end];
    const travelled = Math.max(maxTravel, Math.hypot(dx, dy));
    dragOrigin = null;
    dragPath = [];

    // Travel in any direction counts: an L-shape can end up near where it
    // started on one axis while still being a deliberate gesture.
    if (travelled < gestureThreshold) return;
    swallowContextMenu = true;
    ipcRenderer.send('ytd:gesture', { dx, dy, path });
  },
  true,
);

addEventListener(
  'contextmenu',
  (event) => {
    // Windows fires contextmenu after mouseup, but not every platform agrees, so
    // also check whether the drag currently in progress already qualifies.
    const draggedFar = dragOrigin !== null && maxTravel >= gestureThreshold;
    if (!swallowContextMenu && !draggedFar) return;

    swallowContextMenu = false;
    event.preventDefault();
    event.stopPropagation();
  },
  true,
);
