'use strict';

const path = require('node:path');

const { app, BrowserWindow, dialog, nativeTheme, ipcMain } = require('electron');

const { createYouTubeSession, PARTITION } = require('./session');
const { createNavigationGuard, openExternally } = require('./navigation-guard');
const { buildMenu, HOME_URL } = require('./menu');
const { createLogger, safeUrl } = require('./logger');
const { applyDarkTitleBar } = require('./windows-titlebar');
const { resolveGesture, THRESHOLD_PX } = require('./gesture');
const { nextAngle, transformFor } = require('./rotation');
const windowState = require('./window-state');

const SMOKE_TEST = process.argv.includes('--smoke-test');
const LOGIN_PROBE = process.argv.includes('--login-probe');
const HEADLESS = SMOKE_TEST || LOGIN_PROBE;
/** YouTube's own dark background, used for the window and its title bar. */
const BACKGROUND_COLOR = '#0f0f0f';

/** Generated by `npm run icon`; undefined if it has not been generated yet. */
const APP_ICON = (() => {
  const iconPath = path.join(__dirname, '..', '..', 'build', 'icon.ico');
  return require('node:fs').existsSync(iconPath) ? iconPath : undefined;
})();

/** Diagnostics: trace the passkey ceremony and Google's HTTP responses. */
const TRACE = process.argv.includes('--trace') || process.argv.includes('--trace-webauthn');

/** `--sign-in-identity=chrome` forces the disguise on sign-in pages too. */
const SIGN_IN_IDENTITY =
  process.argv.find((arg) => arg.startsWith('--sign-in-identity='))?.split('=')[1] === 'chrome'
    ? 'chrome'
    : 'electron';

/** @type {BrowserWindow | null} */
let mainWindow = null;
/** @type {ReturnType<typeof import('./identity').createIdentity> | null} */
let identity = null;

if (!HEADLESS && !app.requestSingleInstanceLock()) {
  // Say why. Exiting silently here is indistinguishable from failing to start,
  // and the existing window may be minimised or on another desktop.
  console.log('이미 실행 중인 창이 있습니다. 기존 창을 앞으로 가져오고 종료합니다.');
  app.quit();
} else {
  app.on('second-instance', () => {
    if (!mainWindow) return;
    if (mainWindow.isMinimized()) mainWindow.restore();
    mainWindow.focus();
  });
  start();
}

function start() {
  let log = () => {};
  const guard = createNavigationGuard({
    onNotice: HEADLESS ? undefined : showBlockedNotice,
    log: (text) => log(text),
    childWindowOptions,
  });

  // Popups get the dark title bar too; doing it here covers every window without
  // each creation site having to remember.
  app.on('browser-window-created', (_event, win) => paintTitleBar(win));

  // Rotation geometry for the `R` key. It lives here because a sandboxed preload
  // cannot require application files, and this keeps one tested implementation
  // rather than a copy in the preload that drifts.
  ipcMain.handle('ytd:rotate', (_event, request) => {
    const current = Number(request?.current) || 0;
    const angle = request?.advance === true ? nextAngle(current) : current;
    return { angle, transform: transformFor(angle, request?.box, request?.container) };
  });

  // Right-drag gestures. The renderer reports the drag; the meaning is decided
  // here, where the page cannot influence it.
  ipcMain.on('ytd:gesture', (event, drag) => {
    // The preload is injected into every frame, ads included. Closing a window
    // or walking its history is the top frame's business, not an ad's.
    if (event.senderFrame && event.senderFrame !== event.sender.mainFrame) return;

    const command = resolveGesture(drag);
    if (!command) return;

    if (command === 'close') {
      // Close the window the gesture was drawn in, popup or main.
      BrowserWindow.fromWebContents(event.sender)?.close();
      return;
    }

    const history = event.sender.navigationHistory;
    if (command === 'back' && history.canGoBack()) history.goBack();
    else if (command === 'forward' && history.canGoForward()) history.goForward();
  });

  // Every webContents, including popups opened by the sign-in flow.
  app.on('web-contents-created', (_event, contents) => {
    guard.attach(contents);
    traceNavigation(contents, (text) => log(text));
  });

  app.whenReady().then(async () => {
    // Dark regardless of the Windows setting. This drives the title bar, menu
    // bar, native dialogs and scrollbars — and, because it also sets
    // `prefers-color-scheme`, YouTube's own theme follows along.
    nativeTheme.themeSource = 'dark';

    // An interrupted sign-in can leave a half-established session: a Google
    // cookie with no YouTube session behind it. Google then treats the account
    // as already signed in and never re-runs the flow, so the only way out is to
    // start clean.
    if (process.argv.includes('--reset-session')) {
      const { clearSessionData } = require('./session');
      await clearSessionData();
      console.log('세션을 초기화했습니다.');
      app.exit(0);
      return;
    }

    if (!HEADLESS) {
      const logger = createLogger();
      log = logger.write;
      console.log(`log: ${logger.file}`);
    }

    if (LOGIN_PROBE) {
      const { runLoginProbe } = require('./login-probe');
      app.exit((await runLoginProbe()) ? 0 : 1);
      return;
    }

    const { session: ytSession, identity: sessionIdentity } = createYouTubeSession({
      signInIdentity: SIGN_IN_IDENTITY,
    });
    identity = sessionIdentity;
    guard.installRequestBackstop(ytSession);
    if (TRACE) installNetworkTrace(ytSession, (text) => log(text));

    mainWindow = createWindow();
    buildMenu(mainWindow);

    if (SMOKE_TEST) {
      const { runSmokeTest } = require('./smoke-test');
      const ok = await runSmokeTest({ win: mainWindow, guard, identity });
      app.exit(ok ? 0 : 1);
      return;
    }

    mainWindow.once('ready-to-show', () => mainWindow?.show());
    // YouTube reloads itself with `?themeRefresh=1` on a cold profile, which
    // aborts the original navigation; that rejection is expected, not an error.
    mainWindow.loadURL(HOME_URL).catch((error) => {
      if (!/ERR_ABORTED/.test(String(error))) console.error('load failed:', error);
      mainWindow?.show();
    });
  });

  // Headless runs open and close windows as they go; quitting on the first empty
  // moment would cut the run short.
  if (!HEADLESS) app.on('window-all-closed', () => app.quit());
}

/*
 * There is deliberately no per-navigation `webContents.userAgent` switching here.
 *
 * Identity is applied in `onBeforeSendHeaders`, which acts on one request at a
 * time and cannot disturb a navigation. Assigning `webContents.userAgent` is a
 * different thing entirely: doing it while a redirect is in flight cancels that
 * redirect with ERR_ABORTED.
 *
 * That is not hypothetical. Sign-in ends with a hop from accounts.google.com to
 * accounts.youtube.com — across the identity boundary — and switching the UA
 * there killed the one redirect that completes the login, right after Google had
 * accepted the passkey. The page then fell back to the challenge and span.
 */
/**
 * Record what Google's servers actually answer during sign-in: status, redirect
 * target and whether a cookie was set. A redirect loop is either the server
 * refusing the client (3xx straight back to the challenge) or a cookie that
 * never sticks — and those have completely different fixes.
 *
 * Header *values* are never logged, only a count: they carry session tokens.
 */
function installNetworkTrace(ytSession, log) {
  ytSession.webRequest.onHeadersReceived(
    { urls: ['https://*.google.com/*'] },
    (details, callback) => {
      if (details.resourceType === 'mainFrame' || details.resourceType === 'xhr') {
        const headers = details.responseHeaders ?? {};
        const valueOf = (name) => {
          const key = Object.keys(headers).find((k) => k.toLowerCase() === name);
          return key ? headers[key] : undefined;
        };
        const location = valueOf('location');
        const setCookie = valueOf('set-cookie');
        log(
          `http ${details.statusCode} ${details.method} ${safeUrl(details.url)}` +
            (location ? ` -> ${safeUrl(String(location))}` : '') +
            (setCookie ? ` set-cookie=${setCookie.length}` : ''),
        );
      }
      callback({});
    },
  );

  ytSession.webRequest.onErrorOccurred({ urls: ['https://*.google.com/*'] }, (details) => {
    if (details.resourceType !== 'mainFrame' && details.resourceType !== 'xhr') return;
    log(`neterr ${details.error} ${details.method} ${safeUrl(details.url)}`);
  });
}

/** A page re-entering the same URL this many times is stuck, not navigating. */
const LOOP_THRESHOLD = 12;
const LOOP_WINDOW_MS = 8000;

/** Record the redirect chain so a broken sign-in can be traced afterwards. */
function traceNavigation(contents, log) {
  const recentNavigations = [];

  contents.on('did-start-navigation', (event, legacyUrl, legacyIsInPlace) => {
    if (event.isMainFrame === false) return;
    const url = safeUrl(event.url ?? legacyUrl);

    // Same-document navigations are history updates, not page loads. A page that
    // polls while it waits — which is exactly what the passkey challenge does —
    // emits a stream of them. Counting those as a redirect loop reads a healthy
    // wait as a failure, and stopping the page then breaks the real ceremony.
    const isSameDocument = event.isSameDocument ?? legacyIsInPlace ?? false;
    if (isSameDocument) {
      logSameDocument(url);
      return;
    }

    log(`nav -> ${url}`);
    if (detectLoop(recentNavigations, url)) {
      log(`loop detected at ${url} — stopping`);
      contents.stop();
      showLoopNotice(url);
    }
  });

  // Throttled: these can arrive many times a second and would drown the log.
  let sameDocumentCount = 0;
  let sameDocumentLoggedAt = 0;
  function logSameDocument(url) {
    sameDocumentCount += 1;
    const now = Date.now();
    if (now - sameDocumentLoggedAt < 2000) return;
    sameDocumentLoggedAt = now;
    log(`same-doc x${sameDocumentCount} ${url}`);
  }

  // The page's own errors are the only account of why a sign-in stalled.
  contents.on('console-message', (event) => {
    if (event.level !== 'error' && event.level !== 'warning') return;
    log(`console ${event.level}: ${String(event.message).slice(0, 300)}`);
  });
  contents.on('did-fail-load', (_event, code, description, failedUrl, isMainFrame) => {
    if (!isMainFrame || code === -3) return;
    log(`fail ${description} (${code}) ${safeUrl(failedUrl)}`);
  });
  contents.on('render-process-gone', (_event, details) => log(`renderer gone: ${details.reason}`));
  contents.on('unresponsive', () => log('renderer unresponsive'));
  contents.on('responsive', () => log('renderer responsive again'));
}

/**
 * Keep the title bar dark.
 *
 * Setting the DWM caption colour is not a one-shot operation, which is what the
 * S_OK return value misleadingly suggests. Windows discards it if the window is
 * not on screen yet, and drops it again every time it repaints the frame — after
 * a restore, the caption comes back in the accent colour. So the colour has to be
 * re-asserted on every event that can repaint the frame.
 */
function paintTitleBar(win) {
  let warned = false;
  const paint = () => {
    const result = applyDarkTitleBar(win, { caption: BACKGROUND_COLOR });
    if (result.applied || warned) return;
    warned = true; // once is enough; this fires on every focus
    console.log(`title bar left as-is: ${result.reason}`);
  };

  for (const event of ['ready-to-show', 'show', 'restore', 'focus', 'maximize', 'unmaximize']) {
    win.on(event, paint);
  }
  paint();
}

/**
 * Every window in the app must be built from these, popups included.
 *
 * A window opened with ctrl/shift-click does **not** inherit the opener's
 * `partition`: without it the popup lands on Electron's default session, which
 * has none of the login cookies, so the user appears signed out in the new
 * window. It would also miss the preload, and with it the gesture handling and
 * the userAgentData patch.
 */
function sharedWebPreferences() {
  return {
    partition: PARTITION,
    preload: path.join(__dirname, '..', 'preload', 'index.js'),
    additionalArguments: [
      `--ua-profile=${identity?.profileId ?? 'chrome'}`,
      `--gesture-threshold=${THRESHOLD_PX}`,
      ...(TRACE ? ['--trace-webauthn'] : []),
    ],
    contextIsolation: true,
    nodeIntegration: false,
    sandbox: true,
    webviewTag: false,
    spellcheck: false,
  };
}

/** Options applied to popups the page opens (ctrl/shift-click, `window.open`). */
function childWindowOptions() {
  return {
    backgroundColor: BACKGROUND_COLOR,
    icon: APP_ICON,
    autoHideMenuBar: true,
    webPreferences: sharedWebPreferences(),
  };
}

function createWindow() {
  const state = windowState.read();

  const win = new BrowserWindow({
    x: state.x,
    y: state.y,
    width: state.width,
    height: state.height,
    minWidth: 480,
    minHeight: 360,
    show: false,
    backgroundColor: BACKGROUND_COLOR,
    autoHideMenuBar: false,
    title: 'YouTube',
    // Packaged builds take the icon from the executable; this is what gives the
    // window and taskbar the right icon during `npm start`.
    icon: APP_ICON,
    webPreferences: sharedWebPreferences(),
  });

  if (state.maximized) win.maximize();
  windowState.track(win);
  win.on('closed', () => {
    mainWindow = null;
  });
  return win;
}

/**
 * A Google service outside the YouTube surface was requested. Explain the block
 * and offer the default browser, which does not share this app's session.
 */
/** True once the same URL has been re-entered too often in too short a window. */
function detectLoop(history, url) {
  const now = Date.now();
  history.push({ url, at: now });
  while (history.length > 0 && now - history[0].at > LOOP_WINDOW_MS) history.shift();
  return history.filter((entry) => entry.url === url).length >= LOOP_THRESHOLD;
}

let loopNoticeShown = false;

function showLoopNotice(url) {
  if (loopNoticeShown || !mainWindow) return;
  loopNoticeShown = true;
  dialog.showMessageBox(mainWindow, {
    type: 'warning',
    title: '로그인이 반복되고 있습니다',
    message: '같은 페이지가 계속 다시 열려 중단했습니다.',
    detail:
      `${url}\n\nGoogle이 인증 결과를 받아들이지 않고 되돌려보내는 상태입니다.\n` +
      '메뉴 → 계정 → 로그아웃으로 세션을 지운 뒤 다시 시도해 보세요.\n\n' +
      `자세한 기록: ${app.getPath('userData')}\\ytd.log`,
    buttons: ['확인'],
  });
}

let noticeOpen = false;

async function showBlockedNotice({ url }) {
  // One dialog at a time. A blocked hop in a redirect chain fires repeatedly with
  // a fresh token each time, and stacking modals looks like the app flickering.
  if (!mainWindow || noticeOpen) return;
  noticeOpen = true;

  let host = url;
  try {
    host = new URL(url).host;
  } catch {
    /* keep the raw string */
  }

  try {
    const { response } = await dialog.showMessageBox(mainWindow, {
      type: 'info',
      title: '차단됨',
      message: `${host} 은(는) 이 앱에서 열 수 없습니다.`,
      detail:
        '이 앱의 Google 로그인 세션은 YouTube 전용입니다. Gmail·포토·드라이브 등 다른 ' +
        'Google 서비스로는 접근할 수 없습니다.\n\n기본 브라우저에서 열면 이 앱의 세션은 ' +
        '사용되지 않습니다.',
      buttons: ['닫기', '기본 브라우저에서 열기'],
      defaultId: 0,
      cancelId: 0,
    });
    if (response === 1) openExternally(url);
  } finally {
    noticeOpen = false;
  }
}
